apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sre-bot-system

resources:
  - namespace.yaml
  - crd-sreincident.yaml
  - rbac.yaml
  - watcher-agent.yaml
  - commander-agent.yaml
  - investigator-agent.yaml
  - brain-agent.yaml
  - hil-agent.yaml
  - gitops-agent.yaml
