#!/usr/bin/env bash
# Build sre-bot images locally, import into k3s (lima), helm install.
# Usage: export KUBECONFIG=~/.kube/k3s.yaml && ./scripts/deploy-k3s.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

export KUBECONFIG="${KUBECONFIG:-${HOME}/.kube/k3s.yaml}"
KUBECTL="${KUBECTL:-/opt/homebrew/bin/kubectl}"
LIMA_INSTANCE="${LIMA_INSTANCE:-k3s}"
IMAGE_TAG="${IMAGE_TAG:-k3s-local}"
REGISTRY="${REGISTRY:-ghcr.io}"
OWNER="${OWNER:-rmallam}"
NS="${NS:-sre-bot-system}"
VALUES_FILE="${VALUES_FILE:-helm/k3s-values.local.yaml}"

if ! command -v podman >/dev/null 2>&1; then
  echo "podman not found" >&2
  exit 1
fi
if ! command -v helm >/dev/null 2>&1; then
  echo "helm not found" >&2
  exit 1
fi
if ! "$KUBECTL" get nodes >/dev/null 2>&1; then
  echo "Cannot reach cluster (KUBECONFIG=$KUBECONFIG)" >&2
  exit 1
fi
if ! command -v limactl >/dev/null 2>&1; then
  echo "limactl not found — set K3S_IMPORT_CMD to import images manually" >&2
  exit 1
fi

ENV_FILE="${ENV_FILE:-.env.local}"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing $ENV_FILE" >&2
  exit 1
fi
# shellcheck disable=SC1090
source "$ENV_FILE"

OPENROUTER_API_KEY="${OPENROUTER_API_KEY:-}"
GEMINI_API_KEY="${GEMINI_API_KEY:-}"
OPENAI_API_KEY="${OPENAI_API_KEY:-}"
TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN:-}"
ALLOWED_USERS="${ALLOWED_USERS:-}"
TELEGRAM_ALERT_CHAT_ID="${TELEGRAM_ALERT_CHAT_ID:-${ALLOWED_USERS}}"
SRE_INTERNAL_TOKEN="${SRE_INTERNAL_TOKEN:-sre-bot-local-dev-token}"
LLM_PROVIDER="${LLM_PROVIDER:-auto}"
OLLAMA_BASE_URL="${OLLAMA_BASE_URL:-}"

if [[ -z "$OPENROUTER_API_KEY" && -z "$GEMINI_API_KEY" && -z "$OPENAI_API_KEY" && "$LLM_PROVIDER" != "ollama" && -z "$OLLAMA_BASE_URL" ]]; then
  echo "Set one LLM provider in $ENV_FILE" >&2
  exit 1
fi

POSTGRES_PERSIST="false"
if "$KUBECTL" -n "$NS" get sts postgres >/dev/null 2>&1; then
  POSTGRES_PERSIST="true"
fi

cat > "$VALUES_FILE" <<EOF
# Generated by scripts/deploy-k3s.sh — do not commit
global:
  imageOwner: ${OWNER}
  imageTag: ${IMAGE_TAG}
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []

llm:
  provider: ${LLM_PROVIDER:-auto}
  maxTokens: "${LLM_MAX_TOKENS:-1024}"
  ollama:
    brainModel: ${OLLAMA_BRAIN_MODEL:-qwen2.5:14b}
    commanderModel: ${OLLAMA_COMMANDER_MODEL:-qwen2.5:7b}
    toolSelectModel: ${OLLAMA_TOOL_SELECT_MODEL:-qwen2.5:7b}
    baseUrl: ${OLLAMA_BASE_URL:-http://host.lima.internal:11434/v1}
  openai:
    brainModel: ${OPENAI_BRAIN_MODEL:-gpt-4o}
    commanderModel: ${OPENAI_COMMANDER_MODEL:-gpt-4o-mini}
    toolSelectModel: ${OPENAI_TOOL_SELECT_MODEL:-gpt-4o-mini}
    baseUrl: ${OPENAI_BASE_URL:-https://api.openai.com/v1}

secrets:
  create: true
  openrouterApiKey: "${OPENROUTER_API_KEY}"
  geminiApiKey: "${GEMINI_API_KEY}"
  openaiApiKey: "${OPENAI_API_KEY}"
  allowedUsers: "${ALLOWED_USERS}"
  telegramBotToken: "${TELEGRAM_BOT_TOKEN}"
  telegramAlertChatId: "${TELEGRAM_ALERT_CHAT_ID}"
  gitopsRepoUrl: "${GITOPS_REPO_URL:-}"
  githubToken: "${GITHUB_TOKEN:-}"
  sreInternalToken: "${SRE_INTERNAL_TOKEN}"

agentMode:
  sreAgentMode: ${SRE_AGENT_MODE:-agentic}
  ragGrounding: ${SRE_RAG_GROUNDING:-true}
  ragLearning: true
  platformRouting: true

orchestrator:
  registryDryRun: "${REGISTRY_DRY_RUN:-true}"

postgres:
  persistence:
    enabled: ${POSTGRES_PERSIST}

ragPostgres:
  persistence:
    enabled: ${POSTGRES_PERSIST}

gitops:
  persistence:
    enabled: false

platform:
  routerEncoder: google
  embeddingProvider: google

consoleAuth:
  sessionBackend: redis

e2eFixtures:
  enabled: true

service:
  console:
    type: ClusterIP
  commander:
    type: ClusterIP

ingress:
  hil:
    enabled: false
  console:
    enabled: false
EOF

import_image() {
  local image="$1"
  local archive
  archive="$(mktemp "${TMPDIR:-/tmp}/sre-bot-k3s.XXXXXX.tar")"
  podman save -q "$image" -o "$archive"
  limactl copy "$archive" "${LIMA_INSTANCE}:/tmp/sre-bot-image.tar"
  limactl shell "$LIMA_INSTANCE" -- sudo k3s ctr images import /tmp/sre-bot-image.tar
  limactl shell "$LIMA_INSTANCE" -- sudo rm -f /tmp/sre-bot-image.tar
  rm -f "$archive"
}

build_load() {
  local dockerfile="$1"
  local image="$2"
  echo "    build ${image}"
  podman build -q -t "$image" -f "$dockerfile" "$ROOT"
  echo "    import ${image}"
  import_image "$image"
}

echo "==> Building and importing images (tag=${IMAGE_TAG}, lima=${LIMA_INSTANCE})"

BUILDS=(
  "agents/watcher/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-watcher:${IMAGE_TAG}"
  "agents/commander/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-commander:${IMAGE_TAG}"
  "agents/investigator/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-investigator:${IMAGE_TAG}"
  "agents/debug-mcp/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-debug-mcp:${IMAGE_TAG}"
  "agents/brain/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-brain:${IMAGE_TAG}"
  "agents/orchestrator/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-orchestrator:${IMAGE_TAG}"
  "agents/hil/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-hil:${IMAGE_TAG}"
  "agents/gitops/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-gitops:${IMAGE_TAG}"
  "agents/executor/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-executor:${IMAGE_TAG}"
  "agents/security/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-security:${IMAGE_TAG}"
  "agents/cicd-agent/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-cicd:${IMAGE_TAG}"
  "agents/console/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-console:${IMAGE_TAG}"
  "agents/coding-agent/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-coding-agent:${IMAGE_TAG}"
  "sre-agent-platform/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-platform:${IMAGE_TAG}"
)

for entry in "${BUILDS[@]}"; do
  IFS='|' read -r df img <<< "$entry"
  build_load "$df" "$img"
done

echo "==> Helm install"
helm upgrade --install sre-bot ./helm/sre-bot \
  -f "$VALUES_FILE" \
  --set global.clusterProfile=k3s \
  --kubeconfig "$KUBECONFIG" \
  --namespace "$NS" \
  --create-namespace \
  --wait \
  --timeout 20m

echo "==> Rolling agent deployments"
"$KUBECTL" -n "$NS" rollout restart deployment \
  watcher-agent commander-agent investigator-agent brain-agent orchestrator-agent \
  hil-agent gitops-agent executor-agent security-agent cicd-agent console-agent coding-agent platform-agent
"$KUBECTL" -n "$NS" rollout status deployment --timeout=300s

echo ""
echo "==> Deployed to k3s namespace ${NS} (KUBECONFIG=${KUBECONFIG})"
echo "    Port-forward: KUBECONFIG=${KUBECONFIG} ./scripts/k3s-port-forward.sh"
echo "    Console: http://localhost:9091"
