#!/usr/bin/env bash
# Build sre-bot images locally, load into kind, helm install.
# Usage: ./scripts/deploy-kind.sh [kind-cluster-name]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

KIND_CLUSTER="${1:-test-upgrade-cluster}"
KIND_CONTEXT="kind-${KIND_CLUSTER}"
IMAGE_TAG="${IMAGE_TAG:-kind-local}"
REGISTRY="${REGISTRY:-ghcr.io}"
OWNER="${OWNER:-rmallam}"
PARALLEL="${PARALLEL:-1}"
VALUES_FILE="${VALUES_FILE:-helm/kind-values.local.yaml}"

if ! command -v kind >/dev/null 2>&1; then
  echo "kind not found" >&2
  exit 1
fi
if ! command -v helm >/dev/null 2>&1; then
  echo "helm not found" >&2
  exit 1
fi
if ! command -v podman >/dev/null 2>&1; then
  echo "podman not found" >&2
  exit 1
fi

if ! kubectl --context "$KIND_CONTEXT" get nodes >/dev/null 2>&1; then
  echo "Cannot reach cluster context $KIND_CONTEXT" >&2
  exit 1
fi

ENV_FILE="${ENV_FILE:-.env.local}"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing $ENV_FILE — copy from helm/sre-bot/values-local.example.yaml secrets" >&2
  exit 1
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

OPENROUTER_API_KEY="${OPENROUTER_API_KEY:-}"
GEMINI_API_KEY="${GEMINI_API_KEY:-}"
OPENAI_API_KEY="${OPENAI_API_KEY:-}"
TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN:-}"
ALLOWED_USERS="${ALLOWED_USERS:-}"
TELEGRAM_ALERT_CHAT_ID="${TELEGRAM_ALERT_CHAT_ID:-${ALLOWED_USERS}}"

if [[ -z "$OPENROUTER_API_KEY" && -z "$GEMINI_API_KEY" ]]; then
  echo "Set OPENROUTER_API_KEY or GEMINI_API_KEY in $ENV_FILE" >&2
  exit 1
fi

cat > "$VALUES_FILE" <<EOF
# Generated by scripts/deploy-kind.sh — do not commit
global:
  imageOwner: ${OWNER}
  imageTag: ${IMAGE_TAG}
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []

llm:
  provider: ${LLM_PROVIDER:-openrouter}

secrets:
  create: true
  openrouterApiKey: "${OPENROUTER_API_KEY}"
  geminiApiKey: "${GEMINI_API_KEY}"
  openaiApiKey: "${OPENAI_API_KEY}"
  allowedUsers: "${ALLOWED_USERS}"
  telegramBotToken: "${TELEGRAM_BOT_TOKEN}"
  telegramAlertChatId: "${TELEGRAM_ALERT_CHAT_ID}"
  gitopsRepoUrl: "${GITOPS_REPO_URL:-}"
  githubToken: "${GITHUB_TOKEN:-}"

agentMode:
  sreAgentMode: ${SRE_AGENT_MODE:-agentic}
  ragGrounding: ${SRE_RAG_GROUNDING:-true}
  ragLearning: true
  platformRouting: true

orchestrator:
  registryDryRun: "${REGISTRY_DRY_RUN:-true}"

# kind/local-path: concurrent PVC provisioning can stall — use emptyDir for dev
postgres:
  persistence:
    enabled: false

ragPostgres:
  persistence:
    enabled: false

gitops:
  persistence:
    enabled: false

platform:
  routerEncoder: google
  embeddingProvider: google

service:
  console:
    type: ClusterIP
  commander:
    type: ClusterIP

ingress:
  hil:
    enabled: false
  console:
    enabled: false
EOF

echo "==> Building and loading images (tag=${IMAGE_TAG}, cluster=${KIND_CLUSTER})"

build_load() {
  local dockerfile="$1"
  local image="$2"
  local archive
  archive="$(mktemp "${TMPDIR:-/tmp}/sre-bot-kind.XXXXXX.tar")"
  echo "    build ${image}"
  podman build -q -t "$image" -f "$dockerfile" "$ROOT"
  echo "    load  ${image}"
  podman save -q "$image" -o "$archive"
  kind load image-archive --name "$KIND_CLUSTER" "$archive"
  rm -f "$archive"
}

export ROOT KIND_CLUSTER IMAGE_TAG REGISTRY OWNER
export -f build_load

BUILDS=(
  "agents/watcher/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-watcher:${IMAGE_TAG}"
  "agents/commander/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-commander:${IMAGE_TAG}"
  "agents/investigator/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-investigator:${IMAGE_TAG}"
  "agents/brain/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-brain:${IMAGE_TAG}"
  "agents/orchestrator/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-orchestrator:${IMAGE_TAG}"
  "agents/hil/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-hil:${IMAGE_TAG}"
  "agents/gitops/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-gitops:${IMAGE_TAG}"
  "agents/executor/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-executor:${IMAGE_TAG}"
  "agents/security/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-security:${IMAGE_TAG}"
  "agents/cicd-agent/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-cicd:${IMAGE_TAG}"
  "agents/console/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-console:${IMAGE_TAG}"
  "agents/coding-agent/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-coding-agent:${IMAGE_TAG}"
  "sre-agent-platform/Dockerfile|${REGISTRY}/${OWNER}/sre-bot-platform:${IMAGE_TAG}"
)

for entry in "${BUILDS[@]}"; do
  IFS='|' read -r df img <<< "$entry"
  build_load "$df" "$img"
done

echo "==> Helm install"
helm upgrade --install sre-bot ./helm/sre-bot \
  -f "$VALUES_FILE" \
  --kube-context "$KIND_CONTEXT" \
  --namespace sre-bot-system \
  --create-namespace \
  --wait \
  --timeout 15m

echo ""
echo "==> Deployed to context ${KIND_CONTEXT} namespace sre-bot-system"
echo ""
echo "    Run BOTH compose + kind: use ./scripts/kind-port-forward.sh (908x ports)."
echo "    Compose keeps 808x; kind uses 908x — no conflicts."
echo ""
echo "    ./scripts/kind-port-forward.sh ${KIND_CLUSTER}"
echo ""
echo "    Console:   http://localhost:9091"
echo "    Commander: http://localhost:9081/health"
