/**
 * Deterministic Helm chart scaffold for repos without Kubernetes manifests.
 */

import type { HelmChartPayload, RepoSignals } from './types.js';

export interface HelmGeneratorInput {
  appName: string;
  namespace: string;
  image?: string;
  containerPort?: number;
  repoSignals?: RepoSignals;
  githubRepo?: string;
}

const CHART_VERSION = '0.1.0';
const APP_VERSION = '1.0.0';

export function defaultChartPath(appName: string): string {
  return `deploy/helm/${appName}`;
}

export function generateHelmChart(input: HelmGeneratorInput): HelmChartPayload {
  const app = sanitizeName(input.appName);
  const ns = input.namespace || 'default';
  const port = input.containerPort ?? inferPort(input.repoSignals);
  const image =
    input.image ??
    input.repoSignals?.suggestedImage ??
    `ghcr.io/${normalizeImageRepo(input.githubRepo)}/${app}:latest`;

  const base = defaultChartPath(app);

  const valuesYaml = `replicaCount: 1

image:
  repository: ${imageRepository(image)}
  tag: ${imageTag(image)}
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: ${port}

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

namespace: ${ns}
`;

  const chartYaml = `apiVersion: v2
name: ${app}
description: Helm chart generated by sre-bot for ${app}
type: application
version: ${CHART_VERSION}
appVersion: "${APP_VERSION}"
`;

  const helpersTpl = `{{- define "${app}.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "${app}.fullname" -}}
{{- printf "%s" (include "${app}.name" .) | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "${app}.labels" -}}
app.kubernetes.io/name: {{ include "${app}.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/managed-by: sre-bot
{{- end }}
`;

  const deploymentYaml = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "${app}.fullname" . }}
  labels:
    {{- include "${app}.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "${app}.name" . }}
  template:
    metadata:
      labels:
        {{- include "${app}.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "${app}.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
`;

  const serviceYaml = `apiVersion: v1
kind: Service
metadata:
  name: {{ include "${app}.fullname" . }}
  labels:
    {{- include "${app}.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "${app}.name" . }}
`;

  return {
    files: {
      [`${base}/Chart.yaml`]: chartYaml,
      [`${base}/values.yaml`]: valuesYaml,
      [`${base}/templates/_helpers.tpl`]: helpersTpl,
      [`${base}/templates/deployment.yaml`]: deploymentYaml,
      [`${base}/templates/service.yaml`]: serviceYaml,
    },
  };
}

function sanitizeName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/^-+|-+$/g, '') || 'app';
}

function normalizeImageRepo(githubRepo?: string): string {
  if (!githubRepo) return 'example';
  const slug = githubRepo.replace(/^https?:\/\//, '').replace(/^github\.com\//, '');
  return slug.toLowerCase();
}

function imageRepository(image: string): string {
  const idx = image.lastIndexOf(':');
  return idx > 0 ? image.slice(0, idx) : image;
}

function imageTag(image: string): string {
  const idx = image.lastIndexOf(':');
  return idx > 0 ? image.slice(idx + 1) : 'latest';
}

function inferPort(signals?: RepoSignals): number {
  if (signals?.hasPackageJson) return 3000;
  if (signals?.hasGoMod) return 8080;
  return 8080;
}

export function buildHelmDeployPlan(opts: {
  appName: string;
  namespace: string;
  githubRepo: string;
  gitRef: string;
  repoSignals?: RepoSignals;
  existingManifest?: boolean;
  image?: string;
}): import('./types.js').RemediationPlan {
  const chartPath = defaultChartPath(opts.appName);
  const helmChart = generateHelmChart({
    appName: opts.appName,
    namespace: opts.namespace,
    githubRepo: opts.githubRepo,
    repoSignals: opts.repoSignals,
    image: opts.image,
  });

  return {
    action: 'helm_deploy',
    rootCause: opts.existingManifest
      ? 'Deploy request with existing Helm chart in repository'
      : 'Deploy request — no Kubernetes manifests found; generating Helm chart from repository signals',
    reasoning: opts.existingManifest
      ? 'Repository contains Helm/K8s manifests; deploying via helm_deploy with generated or updated chart layout.'
      : `Created standard Helm chart under ${chartPath}/ based on app name and repo signals (Dockerfile, package.json, etc.).`,
    severity: 'MEDIUM',
    proposedPatch: [],
    targetManifestPath: `${chartPath}/Chart.yaml`,
    commitMessage: `feat(helm): add Helm chart for ${opts.appName} (sre-bot)`,
    rollbackSafe: true,
    helmChart,
    targetRepo: 'both',
    githubRepo: opts.githubRepo,
    gitRef: opts.gitRef,
  };
}
